### ISSUE TITLE
Suggestions to make a great mod even greater

### ISSUE THREAD

**Issue by stevetru1** [redseiko/ComfyMods#11] opened 2022-05-21 16:13 UTC
These are probably on your mental list already, but two things I thought might be useful/nice would be:

1. Toggle shout/whisper/say based on the last one used
2. Allow for stacking or streamlining player names and the associated text:

      **current:**
      Player Name
      Text they send
      
      **optional:**
      Player Name: Text they send

**Comment by redseiko** [comment] 2022-05-21 17:10
Sorry can you elaborate on 1? Like if you perform a shout and the shout is toggled off, to toggle it back on?
Or more specifically can you outline the current behaviour vs the intended behaviour?

As for (2) that is in progress right now.

**Comment by redseiko** [comment] 2022-05-22 22:00
(2) is fixed as of v1.1.0.

Closing this for now, if you can make a new one and elaborate on (1) that'd be appreciated.

**Closed by redseiko** 2022-05-22 22:00 UTC
