### ISSUE TITLE
[Feature request] Option to disable the distance max for talking (Chatter)

### ISSUE THREAD

**Issue by DaveKX** [redseiko/ComfyMods#28] opened 2022-12-18 12:19 UTC
Title, I just find it annoying that you need to use /s every time I need to talk to someone that is very far away from me, and this mod seemed the right place to ask for this feature, thank you :).

**Comment by redseiko** [comment] 2023-01-12 23:14
I'll mark this as a duplicate of #26 and use that for tracking.

**Closed by redseiko** 2023-01-12 23:14 UTC
Labels: duplicate
