### ISSUE TITLE
[Feature Request] ability to set default channel

### ISSUE THREAD

**Issue by SumaniPardia** [redseiko/ComfyMods#29] opened 2022-12-22 20:50 UTC
It would be helpful to be able to set the default chat channel.  We sometimes have new people join our server and not know how to shout and think everyone is ignoring them because we're not in range to hear.  I see other mods used to have this feature but don't see any for the new update.

**Comment by lightsourced** [comment] 2023-01-10 02:44
+1! Would love to have this option having to switch to shout all the time was getting annoying. Would also be neat if you could default to party chat when using the groups mod.

**Comment by redseiko** [comment] 2023-01-12 22:57
Closing this as duplicate of issue #26, see that one for details.

**Closed by redseiko** 2023-01-12 22:57 UTC
Labels: duplicate
